# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Add WHY_DOES_PATH_NOT_WORK directory to PATH
        run: |
          echo "WHY_DOES_PATH_NOT_WORK" >> $GITHUB_PATH

      - name: Check path
        run: |
          echo $PATH
