# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"

      - name: Add Solana CLI directory to PATH
        run: |
          echo "~/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Rust
        # https://stackoverflow.com/questions/57251508/run-rustups-curl-fetched-installer-script-non-interactively
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y

      # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
      # "On a cache miss, the action automatically creates a new cache if the job completes successfully."
      # From Rust example at https://github.com/actions/cache/tree/main
      - name: Restore Rust dependencies from Cache if possible
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install latest
          avm use latest

      - name: Add Anchor bin directory to PATH
        run: |
          echo "~/.avm/bin" >> $GITHUB_PATH

      # git will keep outputting:
      #   hint: Using 'master' as the name for the initial branch. This default branch name
      #   hint: is subject to change.
      # Unless we set this.
      - name: Set a default branch name for git
        run: |
          git config --global init.defaultBranch main

      - name: Check versions
        run: |
          echo $PATH
          solana -V
          rustc -V
          anchor _V
          cargo --list

      - name: Create a blank Anchor project
        run: |
          anchor init project

      - name: Fix missing license warning
        run: |
          cd project
          jq '.LICENSE = "UNLICENSED"' package.json > fixed-package.json
          mv fixed-package.json package.json

      - name: Run anchor build
        run: |
          cd project
          anchor build
          anchor test
